{"errorMessage": "An error occurred (AccessDeniedException) when calling the GetSecretValue operation: User: arn:aws:sts::742629497219:assumed-role/iam_for_lambda/ScratchyCooPark4 is not authorized to perform: secretsmanager:GetSecretValue on resource: bob because no identity-based policy allows the secretsmanager:GetSecretValue action", "errorType": "ClientError", "requestId": "97395620-f214-4189-92dc-08b9e57ddfba", "stackTrace": ["  File \"/var/task/main.py\", line 42, in lambda_handler\n    slack_token = \"Bearer \" + get_secret(\"bob\") # change to where and what e.g. (\"slack\", \"token\") or (\"confluence\", \"server\")\n", "  File \"/var/task/main.py\", line 23, in get_secret\n    get_secret_value_response = client.get_secret_value(SecretId=secret)\n", "  File \"/var/task/botocore/client.py\", line 391, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 719, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}